<a href="https://colab.research.google.com/github/YQ617/code-samples/blob/Data-Analysis-and-Visualization/Yanfei_Qin_Participation_Activity_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Participation Activity 6
### Name: Yanfei Qin
### PennKey: yfqin
### PennID: 51386260

## Activity 1: First lessons with Numpy arrays
described on slide 5 of Lecture-6.pdf (8 points)

### Activity 1 Q1

In [ ]:
import numpy as np

np_array_1d = np.arange(10,22)
np_array_2d = np_array_1d.reshape([3,4])
print('A 3x4 matrix filled with values from 10 to 21 is created below:')
print(np_array_2d)

A 3x4 matrix filled with values from 10 to 21 is created below:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### Activity 1 Q2

In [ ]:
print('A sequence of numbers in the form of a Numpy array from 0 to 100 with gaps of 2 numbers is shown below:')
print(np.linspace(0,100,51))

A sequence of numbers in the form of a Numpy array from 0 to 100 with gaps of 2 numbers is shown below:
[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]


### Activity 1 Q3

In [ ]:
z_array_1d = np.arange(0,20)
z_array_1d #this is the 1-d array Z I chose

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
print('A two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 is shown below:')
row=[]
for i in range(len(z_array_1d)):
  if len(z_array_1d[i:i+3]) == 3:
    row.append(z_array_1d[i:i+3])
  else:
    break

array_2d = np.concatenate(row[:], axis = 0).reshape((len(row), len(row[0])))
print(array_2d)

A two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 is shown below:
[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]]


### Activity 1 Q4

In [ ]:
np_array = np.arange(1,21).reshape([5, 4])
np_array #this is the 5x4 array I choose to work on

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
print ('To extract first and third elements of the second and third rows from a given (5x4) array:')
print(np_array[1:3, ::4])

To extract first and third elements of the second and third rows from a given (5x4) array:
[[5]
 [9]]


## Activity 6: First Exercise in Pandas Series 
described on slide 11 of Lecture-6.pdf (12 points)

In [ ]:
from google.colab import files
files.upload()

Saving example_data.csv to example_data.csv


{'example_data.csv': b'time;place;magType;mag;alert;tsunami\n2018-10-13 11:10:23.560;262km NW of Ozernovskiy, Russia;mww;6.7;green;1\n2018-10-13 04:34:15.580;25km E of Bitung, Indonesia;mww;5.2;green;0\n2018-10-13 00:13:46.220;42km WNW of Sola, Vanuatu;mww;5.7;green;0\n2018-10-12 21:09:49.240;13km E of Nueva Concepcion, Guatemala;mww;5.7;green;0\n2018-10-12 02:52:03.620;128km SE of Kimbe, Papua New Guinea;mww;5.6;green;1\n'}

In [ ]:
import numpy as np

data = np.genfromtxt('example_data.csv', delimiter=';', names=True, dtype=None, encoding='UTF')
data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [ ]:
array_dict = {
    col: np.array([row[i] for row in data])
    for i, col in enumerate(data.dtype.names)
}
array_dict

{'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [ ]:
import pandas as pd

magnitude = pd.Series(array_dict['mag'], name='magnitude')
magnitude

0    6.7
1    5.2
2    5.7
3    5.7
4    5.6
Name: magnitude, dtype: float64

In [ ]:
print('The series has a dttype attribute of: ', magnitude.dtype)
print('The series has a shape attribute of: ', magnitude.shape) #a single column, so only a value for the rows dimension.
print('The series has a values attribute of: ', magnitude.values)
print('The series has an index attribute of: ', magnitude.index)

The series has a dttype attribute of:  float64
The series has a shape attribute of:  (5,)
The series has a values attribute of:  [6.7 5.2 5.7 5.7 5.6]
The series has an index attribute of:  RangeIndex(start=0, stop=5, step=1)


In [ ]:
magnitude_new = pd.Series(array_dict['mag'], name='magnitude_new', index=pd.Index([2, 1, 3, 4, 0]))
magnitude_new

2    6.7
1    5.2
3    5.7
4    5.7
0    5.6
Name: magnitude_new, dtype: float64

In [ ]:
magnitude + magnitude_new

0    12.3
1    10.4
2    12.4
3    11.4
4    11.3
dtype: float64

In the above cell, I add ‘magnitude’ and ‘magnitude_new’ series and print the result. I didn't get any NaN values because the two series all have the pd.Index range from 0 to 4, so all indices can be matched and then summed.


## Use NumPy to solve this problem 

In [ ]:
import numpy as np

def whether_magic_square(matrix):
  if matrix.shape[0] != matrix.shape[1]:
    return 'It is not even a square matrix'

  if np.array_equal(np.sort(matrix.flatten()),np.sort(np.arange(1, matrix.size+1))) == False:
    return 'The matrix is of size nxn, but it does not have all the numbers from 1 to n^2'
  
  # Method 1
  for i in matrix.sum(axis=0):
    if i == matrix.sum(axis=0)[0]:
      continue
    else:
      print("The sums of the columns are not equal to each other")
      break
  for L in matrix.sum(axis=1):
    if L == matrix.sum(axis=1)[0]:
      continue
    else:
      print("The sums of the rows are not equal to each other")
      break
  if sum(np.diag(matrix)) == sum(np.diag(np.fliplr(matrix))) == matrix.sum(axis=1)[0] == matrix.sum(axis=0)[0]:
    print('According to Method 1, the input matrix is a magic sqaure')
  else:
    print('According to Method 1, the input matrix is not a magic square')

  # Method 2 for extra credit
  if(max(matrix.sum(axis=0)) == min(matrix.sum(axis=0)) == max(matrix.sum(axis=1))
     == min((matrix.sum(axis=1))) == sum(np.diag(matrix)) == sum(np.diag(np.fliplr(matrix)))):
    print('According to Method 2, the input matrix is a magic sqaure')
  else:
    print('According to Method 2, the input matrix is not a magic square')

In [ ]:
matrix1 = np.array([[17, 24, 1, 8, 15], 

                 [23, 5, 7, 14, 16],

                [4, 6, 13, 20, 22],

                [10, 12, 19, 21, 3],

                [11, 18, 25, 2, 9]])

In [ ]:
matrix2 = np.array([[6, 3, 10, 15],

                  [9, 16, 5, 4],

                  [7, 2, 11, 14], 

                  [12, 13, 8, 1]])

In [ ]:
whether_magic_square(matrix1)

According to Method 1, the input matrix is a magic sqaure
According to Method 2, the input matrix is a magic sqaure


In [ ]:
whether_magic_square(matrix2)

According to Method 1, the input matrix is a magic sqaure
According to Method 2, the input matrix is a magic sqaure
